name : gitaction


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: hello world 출력
      run: echo hello, world
    - name: directory 출력
      run: ls -al
    - name : python version 출력
      run: python -V
    - name: python package 확인
      run: pip list
    - name: pip 업그레이드
      run: python -m pip install --upgrade pip
    - name: 필요한 패키지 설치 
      run: pip install -r requirements.txt
    - name: 파이썬 스크립트 실행
      run: python test.py
